version: "2"
services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        volumes:
            - ./jenkins_home:/var/jenkins_home
        ports:
            - 8080:8080
        restart: always
        networks:
            network:
                ipv4_address: 192.168.1.1

    build-node:
        # User/pass: root/root
        image: rastasheep/ubuntu-sshd:16.04
        container_name: build-node
        ports:
            - 22:22
        restart: always
        networks:
            network:
                ipv4_address: 192.168.1.2

    gitlab:
        image: gitlab/gitlab-ce:latest
        container_name: gitlab
        volumes:
            - ./gitlab/config:/etc/gitlab \
            - ./gitlab/logs:/var/log/gitlab \
            - ./gitlab/data:/var/opt/gitlab \
        ports:
            - 22:22
            - 80:80
            - 443:443
        restart: always
        networks:
            network:
                ipv4_address: 192.168.1.3

networks:
    network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  192.168.1.0/24
                  gateway: 192.168.1.254
