version: "2"
services:
    systemtest:
        build:
            context: ..
            dockerfile: cicd/install-dockerfile
        image: jenkinsutils
        container_name: jenkinsutils_systemtesting
        network_mode: bridge
        volumes:
            - ..:/jenkinsutils
        command: bash -c "/jenkinsutils/cicd/systemtest.sh"

    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        volumes:
            - ./jenkins_home_test:/var/jenkins_home
        ports:
            - 8080:8080
        networks:
            network:
                ipv4_address: 192.168.2.1

networks:
    network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  192.168.2.0/24
                  gateway: 192.168.2.254
