version: "2.1"
services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins_systemtesting
        logging:
            driver: none
        volumes:
            - ./jenkins_home_test:/var/jenkins_home
        ports:
            - 8080:8080
        healthcheck:
            test: ["CMD", "curl", "-f", "http://192.168.2.1:8080"]
            interval: 10s
            timeout: 3s
            retries: 6
        networks:
            network:
                ipv4_address: 192.168.2.1

    systemtest:
        build:
            context: ..
            dockerfile: cicd/install-dockerfile
        image: jenkinsutils
        container_name: jenkinsutils_systemtesting
        depends_on:
            jenkins:
                condition: service_healthy
        volumes:
          - ../jenkinsutils:/jenkinsutils/jenkinsutils
          - ../tests:/jenkinsutils/tests
          - ../cicd:/jenkinsutils/cicd
        command: /jenkinsutils/cicd/systemtest.sh
        networks:
            network:
                ipv4_address: 192.168.2.2

networks:
    network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  192.168.2.0/24
                  gateway: 192.168.2.254
